# Generated by Django 5.2.8 on 2025-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imię', models.CharField(max_length=100)),
                ('Nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Numer_telefonu', models.CharField(blank=True, help_text='Np. 123 456 789', max_length=20, null=True)),
                ('Adres', models.CharField(max_length=200)),
                ('Data_urodzenia', models.DateField(blank=True, help_text='DD-M-RRRR', null=True)),
                ('Bliska_osoba_do_kontaktu', models.CharField(max_length=100)),
                ('Numer_osoby_do_kontaktu', models.CharField(blank=True, help_text='Np. 123 456 789', max_length=20, null=True)),
                ('Wizyta_opłacona', models.BooleanField(default=False)),
            ],
        ),
    ]
