# Generated by Django 5.2.8 on 2025-12-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='Plik',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
