# Generated by Django 5.2.8 on 2025-12-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0002_klient_plik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='Adres',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='Bliska_osoba_do_kontaktu',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='Data_urodzenia',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='Imię',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='Nazwisko',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='Numer_osoby_do_kontaktu',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='Numer_telefonu',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='Plik',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='Wizyta_opłacona',
        ),
        migrations.AddField(
            model_name='klient',
            name='imie',
            field=models.CharField(default='Brak nazwiska', max_length=100, verbose_name='Imię'),
        ),
        migrations.AddField(
            model_name='klient',
            name='wizyta_oplacona',
            field=models.BooleanField(default=False, verbose_name='Wizyta opłacona'),
        ),
        migrations.AddField(
            model_name='klient',
            name='adres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='klient',
            name='bliska_osoba_do_kontaktu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bliska osoba do kontaktu'),
        ),
        migrations.AddField(
            model_name='klient',
            name='data_urodzenia',
            field=models.DateField(blank=True, help_text='DD-M-RRRR', null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AddField(
            model_name='klient',
            name='nazwisko',
            field=models.CharField(blank=True, default='Brak nazwiska', max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AddField(
            model_name='klient',
            name='numer_osoby_do_kontaktu',
            field=models.CharField(blank=True, help_text='Np. 123 456 789', max_length=20, null=True, verbose_name='Numer osoby do kontaktu'),
        ),
        migrations.AddField(
            model_name='klient',
            name='numer_telefonu',
            field=models.CharField(blank=True, default='Brak numeru', help_text='Np. 123 456 789', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='plik',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Plik'),
        ),
    ]
