# Generated by Django 5.2.8 on 2025-12-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_rename_calendarrelation_content_type_object_id_schedule_ca_content_cddadb_idx_and_more'),
        ('system_rejestracji', '0003_delete_document_remove_klient_adres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_rejestracji.klient')),
            ],
            bases=('schedule.event',),
        ),
    ]
