# Generated by Django 5.2.8 on 2025-12-30 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0004_wizyta'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizyta',
            name='status',
            field=models.CharField(choices=[('planowana', 'Planowana'), ('odbyta', 'Odbyta'), ('anulowana', 'Anulowana')], default='planowana', max_length=20),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='system_rejestracji.klient'),
        ),
    ]
