# Generated by Django 5.2.8 on 2025-12-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0005_wizyta_status_alter_wizyta_klient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'verbose_name': 'Wizyta', 'verbose_name_plural': 'Wizyty'},
        ),
        migrations.AddField(
            model_name='wizyta',
            name='zalacznik',
            field=models.FileField(blank=True, null=True, upload_to='wizyty/'),
        ),
    ]
