# Generated by Django 5.2.8 on 2025-12-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0006_alter_wizyta_options_wizyta_zalacznik'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizyta',
            name='wizyta_oplacona',
            field=models.BooleanField(default=False, verbose_name='Wizyta opłacona'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='status',
            field=models.CharField(choices=[('planowana', 'Planowana'), ('odbyta', 'Odbyta'), ('anulowana', 'Anulowana')], default=' ', max_length=20),
        ),
    ]
