# Generated by Django 5.2.8 on 2025-12-30 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0007_wizyta_wizyta_oplacona_alter_wizyta_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlokadaCzasu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('opis', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='wizyta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
