# Generated by Django 5.2.8 on 2025-12-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0008_blokadaczasu_wizyta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='status',
            field=models.CharField(choices=[('potwierdzona', 'Potwierdzona'), ('odbyta', 'Odbyta'), ('anulowana', 'Anulowana')], default=' ', max_length=20),
        ),
    ]
