# Generated by Django 5.2.8 on 2025-12-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0009_alter_wizyta_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlokadaCzasu',
        ),
    ]
