# Generated by Django 5.2.8 on 2025-12-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0010_delete_blokadaczasu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='status',
            field=models.CharField(choices=[('potwierdzona', 'Potwierdzona'), ('odbyta', 'Odbyta'), ('anulowana', 'Anulowana')], default='potwierdzona', max_length=20),
        ),
    ]
