# Generated by Django 5.2.8 on 2025-12-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0011_alter_wizyta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizyta',
            name='godzina_konca',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina zakończenia'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='godzina_startu',
            field=models.TimeField(default='07:00', verbose_name='Godzina rozpoczęcia'),
        ),
    ]
