# Generated by Django 5.2.8 on 2025-12-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0012_wizyta_godzina_konca_wizyta_godzina_startu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='godzina_startu',
            field=models.TimeField(verbose_name='Godzina rozpoczęcia'),
        ),
    ]
