# Generated by Django 5.2.8 on 2025-12-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0013_alter_wizyta_godzina_startu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizyta',
            name='godzina_konca',
        ),
        migrations.RemoveField(
            model_name='wizyta',
            name='godzina_startu',
        ),
    ]
