# Generated by Django 5.2.8 on 2025-12-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0014_remove_wizyta_godzina_konca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienci'},
        ),
    ]
