# Generated by Django 5.2.8 on 2025-12-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0015_alter_klient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='imie',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='numer_telefonu',
            field=models.CharField(blank=True, help_text='Np. 123 456 789', max_length=20, null=True),
        ),
    ]
