# Generated by Django 5.2.8 on 2026-01-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0016_alter_klient_imie_alter_klient_nazwisko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizyta',
            name='kwota',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kwota'),
        ),
    ]
