# Generated by Django 5.2.8 on 2026-01-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_rejestracji', '0017_wizyta_kwota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='wizyta_oplacona',
        ),
    ]
